const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { parseWorld, Game } = require('../world.js');
const original = fs.readFileSync(path.join(__dirname, '../map.txt'), 'utf8');
const room = (name, exits = '', extra = '') => `ЛОКАЦИЯ\n${name}\nОПИСАНИЕ\nЗдесь [стол].\nПЕРЕХОДЫ\n${exits}\nОБЪЕКТЫ\n[стол]\nПустой стол.\n${extra}\n`;
const rooms = room('А', 'восток -> Б') + room('Б', 'запад -> А\nюг -> В') + room('В', 'север -> Б');
const npc = (name = 'Гость', route = 'А, Б, В', gender = '') => `ПЕРСОНАЖ\n${name}\nОПИСАНИЕ\nПутешественник.\nМАРШРУТ\n${route}\n${gender ? `РОД\n${gender}\n` : ''}ДИАЛОГ\nА\n${name}: Добрый вечер.\nИгрок: Здравствуйте.\n${name}: До встречи.\n`;

test('глобальные блоки исходного TXT отделены от комнат: кот, 4 диалога, 2 связи, финал', () => {
  const world = parseWorld(original);
  assert.equal(world.characters.size, 1);
  assert.equal(world.characters.get('Кот').dialogues.size, 4);
  assert.equal(world.connections.length, 2);
  assert.equal(world.connections[0].item, 'отмычка');
  assert.doesNotMatch(world.connections[0].result, /входная дверь|РЕЗУЛЬТАТ/);
  assert.equal(world.connections[1].action, 'Выйти из библиотеки');
  assert.equal(world.endings[0].action, 'Выйти из библиотеки');
  assert.equal(world.locations.get('Холл').items.size, 0);
});
test('NPC ждёт 2 полных такта; третий даёт ход, потом задержка начинается заново', () => {
  const game = new Game(parseWorld(rooms + npc()), () => 0);
  const guest = game.characters.get('Гость');
  assert.equal(guest.ticks, 0);
  game.inspect('стол');
  assert.equal(guest.location, 'А'); assert.equal(guest.ticks, 1);
  game.inspect('стол');
  assert.equal(guest.location, 'А'); assert.equal(guest.ticks, 2);
  game.inspect('стол');
  assert.equal(guest.location, 'Б'); assert.equal(guest.ticks, 0);
  assert.deepEqual(game.events, ['Гость → на восток.']);
  game.inspect('стол'); game.inspect('стол');
  assert.equal(guest.location, 'Б'); assert.equal(guest.ticks, 2);
  game.inspect('стол');
  assert.equal(guest.location, 'А');
  assert.deepEqual(game.events, ['Гость ← с востока.']);
});
test('вероятность движения 35%; нет телепортации между пунктами маршрута', () => {
  const stay = new Game(parseWorld(rooms + npc()), () => .35);
  for (let i = 0; i < 20; i++) stay.inspect('стол');
  assert.equal(stay.characters.get('Гость').location, 'А');
  const move = new Game(stay.world, () => .349);
  for (let i = 0; i < 3; i++) move.inspect('стол');
  assert.equal(move.characters.get('Гость').location, 'Б');
  const disconnected = new Game(parseWorld(rooms + npc('Гость', 'А, В')), () => 0);
  for (let i = 0; i < 20; i++) disconnected.inspect('стол');
  assert.equal(disconnected.characters.get('Гость').location, 'А');
});
test('несколько персонажей, односторонние связи и независимые счётчики', () => {
  const game = new Game(parseWorld(room('А', 'восток -> Б') + room('Б') + npc('Первый', 'А, Б') + npc('Второй', 'Б, А')), () => 0);
  assert.equal(game.presentCharacters.length, 1);
  game.inspect('стол'); game.inspect('стол'); game.inspect('стол');
  assert.equal(game.characters.get('Первый').location, 'Б');
  assert.equal(game.characters.get('Второй').location, 'Б');
  assert.equal(game.characters.get('Первый').ticks, 0);
  assert.equal(game.characters.get('Второй').ticks, 3);
  game.move('Б');
  assert.equal(game.presentCharacters.length, 2);
});
test('события относятся только к видимому движению и не накапливаются', () => {
  const game = new Game(parseWorld(rooms + npc('Гость', 'Б, В')), () => .8);
  // Выбираем южный выход при успешном броске вероятности.
  const rolls = [0, .9];
  game.random = () => rolls.shift() ?? .9;
  game.inspect('стол'); game.inspect('стол'); game.inspect('стол');
  assert.equal(game.characters.get('Гость').location, 'В');
  assert.deepEqual(game.events, []);
  game.move('Б');
  assert.deepEqual(game.events, ['Вы идёте на восток.']);
  game.inspect('стол');
  assert.deepEqual(game.events, []);
});
test('направления прихода противоположны направлению шага; явный род учитывается', () => {
  const game = new Game(parseWorld(rooms + npc('Проводница', 'А, Б', 'женский')), () => 0);
  const character = game.characters.get('Проводница');
  assert.equal(game.movementText(character, 'север', false), 'Проводница ушла на север.');
  assert.equal(game.movementText(character, 'север', true), 'Проводница пришла с юга.');
  assert.equal(game.movementText(character, 'юг', true), 'Проводница пришла с севера.');
  assert.equal(game.movementText(character, 'запад', true), 'Проводница пришла с востока.');
  assert.equal(game.movementText(character, 'восток', true), 'Проводница пришла с запада.');
});
test('диалог раскрывается по реплике; единственный такт после последней, повтор начинается заново', () => {
  const game = new Game(parseWorld(rooms + npc()), () => .99);
  assert.equal(game.inspectCharacter('Гость'), true);
  assert.equal(game.turns, 0);
  assert.equal(game.startDialogue('Гость'), true);
  assert.equal(game.dialogue.shown, 1); assert.equal(game.turns, 0);
  game.nextDialogue();
  assert.equal(game.dialogue.shown, 2); assert.equal(game.turns, 0);
  game.nextDialogue();
  assert.equal(game.dialogue.shown, 3); assert.equal(game.turns, 1);
  assert.equal(game.dialogue.status, 'complete');
  assert.equal(game.nextDialogue(), false); assert.equal(game.turns, 1);
  game.startDialogue('Гость');
  assert.equal(game.dialogue.shown, 1);
  game.inspect('стол');
  assert.equal(game.dialogue.status, 'interrupted');
  assert.equal(game.nextDialogue(), false);
});
test('последняя реплика сохраняется, даже если персонаж уходит в такт завершения', () => {
  const game = new Game(parseWorld(rooms + npc()), () => 0);
  game.inspect('стол'); game.inspect('стол');
  game.startDialogue('Гость'); game.nextDialogue(); game.nextDialogue();
  assert.equal(game.characters.get('Гость').location, 'Б');
  assert.equal(game.dialogue.status, 'complete');
  assert.equal(game.dialogue.shown, 3);
  assert.equal(game.dialogue.lines.at(-1).text, 'До встречи.');
  assert.equal(game.startDialogue('Гость'), false);
});
test('одна реплика завершает диалог сразу; отсутствие диалога не создаёт такт', () => {
  const world = parseWorld(rooms + npc().replace('Игрок: Здравствуйте.\nГость: До встречи.\n', ''));
  const game = new Game(world, () => .99);
  game.startDialogue('Гость');
  assert.equal(game.dialogue.status, 'complete'); assert.equal(game.turns, 1);
  game.move('Б');
  assert.equal(game.dialogue, null);
  assert.equal(game.startDialogue('Гость'), false); assert.equal(game.turns, 2);
});
test('полное прохождение исходного мира и полный сброс состояния', () => {
  const world = parseWorld(original);
  const game = new Game(world, () => .99);
  assert.equal(game.performAction('входная дверь', '1'), false);
  assert.equal(game.move('Холл'), true);
  game.move('Служебное помещение');
  game.inspect('шкафчик с инструментами'); game.take('отмычка');
  assert.equal(game.move('Архив'), true);
  game.inspect('металлический шкаф');
  assert.equal(game.availableApplications('металлический шкаф').length, 1);
  const ticks = game.turns;
  assert.equal(game.apply('металлический шкаф', '0'), true);
  assert.equal(game.turns, ticks + 1);
  assert.equal(game.message.kind, 'result');
  assert.equal(game.apply('металлический шкаф', '0'), false);
  assert.equal(game.turns, ticks + 1);
  game.move('Читальный зал'); game.move('Архив');
  game.inspect('металлический шкаф');
  assert.match(game.message.text, /\{ключ\}/);
  assert.equal(game.take('ключ'), true);
  assert.equal(game.take('ключ'), false);
  assert.equal(game.move('Читальный зал'), true);
  assert.equal(game.move('Холл'), true);
  game.inspect('входная дверь');
  assert.equal(game.availableActions('входная дверь').length, 0);
  assert.equal(game.apply('входная дверь', '1'), true);
  assert.equal(game.availableActions('входная дверь')[0].action, 'Выйти из библиотеки');
  assert.equal(game.ending, null);
  assert.equal(game.performAction('входная дверь', '1'), true);
  assert.match(game.ending.text, /^Вы толкаете дверь/);
  assert.equal(game.ending.button, 'Начать сначала');
  assert.equal(game.move('Архив'), false);
  assert.equal(game.inspect('входная дверь'), false);
  const fresh = new Game(world);
  assert.equal(fresh.current, world.start);
  assert.equal(fresh.visited.size, 1); assert.equal(fresh.firstVisit, true);
  assert.equal(fresh.inventory.size, 0); assert.equal(fresh.foundItems.size, 0);
  assert.equal(fresh.completedLinks.size, 0); assert.equal(fresh.objectStates.size, 0);
  assert.equal(fresh.performedActions.size, 0); assert.equal(fresh.ending, null);
  assert.equal(fresh.dialogue, null); assert.equal(fresh.turns, 0);
  assert.equal(fresh.characters.get('Кот').location, 'Читальный зал');
  assert.equal(fresh.characters.get('Кот').ticks, 0);
});
test('несколько связей одного объекта сохраняют результаты и невзятые предметы', () => {
  const source = 'ЛОКАЦИЯ\nКомната\nОПИСАНИЕ\nЗдесь {токен} и [машина].\nОБЪЕКТЫ\n[машина]\nВыключена.\nПРЕДМЕТЫ\n{токен}\nЖетон.\n{запчасть}\nДеталь.\n{приз}\nНаграда.\nСВЯЗАННЫЕ ОБЪЕКТЫ\n{токен} -> [машина]\nРЕЗУЛЬТАТ\nВыпала {запчасть}.\n{запчасть} -> [машина]\nРЕЗУЛЬТАТ\nПоявился {приз}.\nДЕЙСТВИЕ\nЗабрать награду\nКОНЕЦ ИГРЫ\nУСЛОВИЕ\nИгрок выбрал действие «Забрать награду».\nТЕКСТ\nПобеда!\nКНОПКА\nЕщё раз';
  const game = new Game(parseWorld(source));
  game.take('токен');
  assert.equal(game.availableApplications('машина').length, 1);
  game.apply('машина', '0'); game.take('запчасть'); game.apply('машина', '1');
  game.inspect('машина');
  assert.match(game.message.text, /\{запчасть\}/); assert.match(game.message.text, /\{приз\}/);
  assert.equal(game.take('приз'), true);
  assert.equal(game.availableApplications('машина').length, 0);
  game.performAction('машина', '1');
  assert.equal(game.ending.button, 'Ещё раз');
});
test('ошибки маршрута, связей и условий объясняются без исполнения текста', () => {
  assert.throws(() => parseWorld(rooms + npc('Гость', 'Неизвестно')), /неизвестная локация маршрута/);
  assert.throws(() => parseWorld(rooms + npc('Гость', ', ,')), /маршрут должен содержать/);
  assert.throws(() => parseWorld(rooms + npc() + npc()), /Персонаж.*дважды/);
  assert.throws(() => parseWorld(rooms + 'СВЯЗАННЫЕ ОБЪЕКТЫ\n{нет} -> [стол]\nРЕЗУЛЬТАТ\nЧто-то.'), /предмет.*не определён/);
  assert.throws(() => parseWorld(rooms + 'КОНЕЦ ИГРЫ\nУСЛОВИЕ\nalert(1)\nТЕКСТ\nКонец.\nКНОПКА\nЗаново'), /УСЛОВИЕ финала/);
});
